FROM mcr.microsoft.com/dotnet/sdk:9.0 AS build
WORKDIR /src

COPY ["Lab1/Lab1.csproj", "Lab1/"]
COPY ["Common/Common.csproj", "Common/"]
COPY ["Models/Models.csproj", "Models/"]
COPY ["Migrations/Migrations.csproj", "Migrations/"]

RUN dotnet restore "Lab1/Lab1.csproj"

COPY . .

WORKDIR "/src/Lab1"
RUN dotnet publish "Lab1.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:9.0
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "Lab1.dll"]