@Lab1_HostAddress = http://localhost:5128

GET {{Lab1_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{Lab1_HostAddress}}/api/v1/orders
Content-Type: application/json

{
  "customerId": 1,
  "deliveryAddress": "123 Main St",
  "totalPrice": 100.0,
  "totalPriceCurrency": "USD",
  "orderItems": [
    {
      "productTitle": "Test Product",
      "productUrl": "http://example.com",
      "price": 50.0,
      "priceCurrency": "USD",
      "quantity": 2
    }
  ]
}

###
